css:
  sourceDir:
    - 'web/app/themes/base-theme/scss/'
  mainFile: 'main.scss'
  watchDir: 'web/app/themes/wp-base/scss/**/*.scss'
  destDir: 'web/app/themes/wp-base/assets/css'


js:
  source:
    - './node_modules/bootstrap/dist/js/bootstrap.min.js'
  destDir: 'web/app/themes/base-theme/assets/lib'


browserSync:
  watchDir:
    - 'web/app/themes/base-theme/**/*.php'
    - 'web/app/themes/base-theme/**/*.js'
  proxy: 'yorckshare.test'
  port: 3000
  ui:
    port: 3001